version: '2'
services:
  shard1:
    container_name: shard1
    image: mongo
    command: mongod --shardsvr --replSet shard_replica --dbpath /data/db --port 27017 --bind_ip 0.0.0.0
    ports:
      - 40001:27017
    environment:
      TERM: xterm
    expose:
      - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/ecommerce-db/new/data1:/data/db
  shard2:
    container_name: shard2
    image: mongo
    command: mongod --shardsvr --replSet shard_replica --dbpath /data/db --port 27017 --bind_ip 0.0.0.0
    environment:
      TERM: xterm
    ports:
      - 40002:27017
    expose:
      - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/ecommerce-db/new/data2:/data/db
  shard3:
    container_name: shard3
    image: mongo
    command: mongod --shardsvr --replSet shard_replica --dbpath /data/db --port 27017 --bind_ip 0.0.0.0
    environment:
      TERM: xterm
    ports:
      - 40003:27017
    expose:
      - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/ecommerce-db/new/data3:/data/db

  shard4:
    container_name: shard4
    image: mongo
    command: mongod --shardsvr --replSet shard_replica2 --dbpath /data/db --port 27017 --bind_ip 0.0.0.0
    ports:
      - 30001:27017
    environment:
      TERM: xterm
    expose:
      - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/ecommerce-db/new/data4:/data/db

  shard5:
    container_name: shard5
    image: mongo
    command: mongod --shardsvr --replSet shard_replica2 --dbpath /data/db --port 27017 --bind_ip 0.0.0.0
    environment:
      TERM: xterm
    ports:
      - 30002:27017
    expose:
      - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/ecommerce-db/new/data5:/data/db

  shard6:
    container_name: shard6
    image: mongo
    command: mongod --shardsvr --replSet shard_replica2 --dbpath /data/db --port 27017 --bind_ip 0.0.0.0
    environment:
      TERM: xterm
    ports:
      - 30003:27017
    expose:
      - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/ecommerce-db/new/data6:/data/db


  cfg1:
    container_name: cfg1 
    image: mongo
    command: mongod --configsvr --replSet conf_replica --dbpath /data/db --port 27017 --bind_ip 0.0.0.0
    environment:
      TERM: xterm
    ports:
      - 50001:27017
    expose:
      - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/ecommerce-db/new/config1:/data/db
  cfg2:
    container_name: cfg2
    image: mongo
    command: mongod --configsvr --replSet conf_replica --dbpath /data/db --port 27017 --bind_ip 0.0.0.0
    ports:
      - 50002:27017
    expose:
      - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/ecommerce-db/new/config2:/data/db
  cfg3:
    container_name: cfg3
    image: mongo
    command: mongod --configsvr --replSet conf_replica --dbpath /data/db --port 27017 --bind_ip 0.0.0.0
    environment:
      TERM: xterm
    ports:
      - 50003:27017
    expose:
      - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/ecommerce-db/new/config3:/data/db


  mongos:
    container_name: mongos
    image: mongo
    depends_on:
      - cfg1
      - cfg2
      - cfg3
      - shard1
      - shard2
      - shard3
      - shard4
      - shard5
      - shard6

    command: mongos --configdb conf_replica/cfg1:27017,cfg2:27017,cfg3:27017 --port 27017 --bind_ip 0.0.0.0
    environment:
      TERM: xterm
    ports:
      - 27019:27017
    expose:
      - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro