# Generated by Django 3.2.9 on 2021-12-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211207_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_size',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
