# Generated by Django 3.2.9 on 2021-12-07 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20211207_0628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='maker',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='share',
            name='product',
        ),
        migrations.RemoveField(
            model_name='share',
            name='share_holder',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='reciever',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Gift',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Share',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
