# Generated by Django 4.0 on 2021-12-07 14:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_transaction_share_order_gift'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-date_added',)},
        ),
        migrations.AddField(
            model_name='order',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 12, 7, 14, 33, 32, 60531, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
